# Generated by Django 2.2.13 on 2020-12-24 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Modelo_Inicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quien', models.CharField(max_length=1000)),
                ('mision', models.CharField(max_length=1000)),
                ('vision', models.CharField(max_length=1000)),
                ('foto1', models.ImageField(upload_to='img/inicio')),
                ('foto2', models.ImageField(upload_to='img/inicio')),
            ],
        ),
        migrations.CreateModel(
            name='Modelo_Productos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='img/productos')),
                ('nombre', models.CharField(max_length=500)),
                ('descripsión', models.CharField(max_length=1000)),
                ('presió', models.IntegerField()),
            ],
        ),
    ]
