# Generated by Django 3.1.7 on 2021-03-04 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modelo_Proyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=1000)),
                ('informacion', models.CharField(max_length=1000)),
                ('etapa_titulo_1', models.CharField(max_length=1000)),
                ('etapa_texto_1', models.CharField(max_length=1000)),
                ('etapa_titulo_2', models.CharField(max_length=1000)),
                ('etapa_texto_2', models.CharField(max_length=1000)),
                ('etapa_titulo_3', models.CharField(max_length=1000)),
                ('etapa_texto_3', models.CharField(max_length=1000)),
                ('titulo_imagen', models.CharField(max_length=1000)),
                ('imagen_1', models.ImageField(upload_to='img/proyecto')),
                ('imagen_2', models.ImageField(upload_to='img/proyecto')),
                ('imagen_suptitulo_1', models.CharField(max_length=1000)),
                ('imagen_suptitulo_2', models.CharField(max_length=1000)),
            ],
        ),
    ]
